/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Lenovo
 */
public class FormPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form FoemMember
     */
    boolean x;
    public FormPelanggan() {
        initComponents();
        change2plg();
    }
private void change2member(){
        kode.setText("Id Member");
        nama.setText("Nama Member");
        idtelp.setText("No. Telp");
        telpalamat.setText("Alamat");
        jLabel1.setText("MEMBER");
        cbMember.setVisible(false);
        txtIdTelp.setVisible(true);
        formpelanggan.setVisible(true);
        formMember.setVisible(false);
        btnInsert.setText("INSERT");
        x = true;
    }
    
    private void change2plg(){
        kode.setText("Kode Pelanggan");
        nama.setText("Nama Pelanggan");
        idtelp.setText("Id Member");
        telpalamat.setText("No. Telpon");
        jLabel1.setText("PELANGGAN");
        cbMember.setVisible(true);
        txtIdTelp.setVisible(false);
        formpelanggan.setVisible(false);
        formMember.setVisible(true);
        btnInsert.setText("INSERT");
        x = false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kode = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        idtelp = new javax.swing.JLabel();
        cbMember = new javax.swing.JComboBox();
        txtIdTelp = new javax.swing.JTextField();
        telpalamat = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        formMember = new javax.swing.JLabel();
        formpelanggan = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1152, 688));
        getContentPane().setLayout(null);

        jLabel13.setText("-----------------------------------------");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 190, 170, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setText("PELANGGAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 250, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Keluar");
        jLabel3.setMaximumSize(new java.awt.Dimension(109, 29));
        jLabel3.setMinimumSize(new java.awt.Dimension(109, 29));
        jLabel3.setPreferredSize(new java.awt.Dimension(109, 29));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 450, 70, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Home");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 210, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Pelanggan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 250, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Penyewaan");
        jLabel6.setMaximumSize(new java.awt.Dimension(109, 29));
        jLabel6.setMinimumSize(new java.awt.Dimension(109, 29));
        jLabel6.setPreferredSize(new java.awt.Dimension(109, 29));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Pemesanan");
        jLabel7.setMaximumSize(new java.awt.Dimension(109, 29));
        jLabel7.setMinimumSize(new java.awt.Dimension(109, 29));
        jLabel7.setPreferredSize(new java.awt.Dimension(109, 29));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 330, 130, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Pembayaran");
        jLabel8.setMaximumSize(new java.awt.Dimension(109, 29));
        jLabel8.setMinimumSize(new java.awt.Dimension(109, 29));
        jLabel8.setPreferredSize(new java.awt.Dimension(109, 29));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 370, 140, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Report");
        jLabel9.setMaximumSize(new java.awt.Dimension(109, 29));
        jLabel9.setMinimumSize(new java.awt.Dimension(109, 29));
        jLabel9.setPreferredSize(new java.awt.Dimension(109, 29));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 410, 80, 30);

        kode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kode.setText("Kode Pelanggan");
        getContentPane().add(kode);
        kode.setBounds(380, 130, 170, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 170, 180, 30);

        nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nama.setText("Nama Pelanggan");
        getContentPane().add(nama);
        nama.setBounds(380, 200, 170, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(380, 230, 180, 30);

        idtelp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idtelp.setText("ID Member");
        getContentPane().add(idtelp);
        idtelp.setBounds(380, 270, 170, 20);

        cbMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMemberActionPerformed(evt);
            }
        });
        getContentPane().add(cbMember);
        cbMember.setBounds(380, 300, 180, 30);
        getContentPane().add(txtIdTelp);
        txtIdTelp.setBounds(380, 300, 180, 30);

        telpalamat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telpalamat.setText("No.Telepon");
        getContentPane().add(telpalamat);
        telpalamat.setBounds(380, 340, 170, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(380, 370, 180, 30);

        formMember.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        formMember.setText("Daftar Member ?");
        formMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMemberMouseClicked(evt);
            }
        });
        getContentPane().add(formMember);
        formMember.setBounds(420, 520, 120, 17);

        formpelanggan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        formpelanggan.setText("Input Pelanggan");
        formpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formpelangganMouseClicked(evt);
            }
        });
        getContentPane().add(formpelanggan);
        formpelanggan.setBounds(420, 520, 120, 17);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(490, 420, 70, 40);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(380, 420, 80, 40);

        jToggleButton1.setText("Delete");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(440, 470, 70, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Daftar Pelanggan");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(780, 120, 140, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(630, 160, 452, 90);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Daftar Member");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(780, 270, 140, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(630, 310, 452, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pelanggan (1).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 1152, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMemberActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertActionPerformed

    private void formMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMemberMouseClicked
        change2member();
    }//GEN-LAST:event_formMemberMouseClicked

    private void formpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formpelangganMouseClicked
        // TODO add your handling code here:
        change2plg();
    }//GEN-LAST:event_formpelangganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cbMember;
    private javax.swing.JLabel formMember;
    private javax.swing.JLabel formpelanggan;
    private javax.swing.JLabel idtelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel kode;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel telpalamat;
    private javax.swing.JTextField txtIdTelp;
    // End of variables declaration//GEN-END:variables
}
